data:
  npz: src/output/rgen/train_10min.npz
train:
  epochs: 1000
  batch_size: 32
  lr: 0.001
  weight_decay: 0.0001
  grad_clip: 1.0
  beta_target: 1.0
  beta_warm_frac: 0.3
  lambda_tv: 0.01
  lambda_home: 0.1
  val_frac: 0.1
  # population calibration losses
  lambda_tod: 0.0
  lambda_presence: 0.0

model:
  method: "auto_pds"
  z_dim: 16
  emb_dim: 128
  cnn_channels: [64, 64]
  cnn_kernel: 5
  cnn_dropout: 0.1
  pds_path: src/output/rgen/runs/exp_phase2/phase2_pds.npz